### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [ramakrishnareddy18113/github-for-developers-3#3]
We should all create great bios in this project. Make sure your bio includes:

```
     - [ ] Your name
     - [ ] Where you are from
     - [ ] A favorite food
     - [ ] A hobby
```

**Comment by ramakrishnareddy18113** [comment]
**Name**: _RAM_
**From**:_INDIA_
**Favorite Food**:_Fish_
**Hobby**:_Surfing_
